#the folling are dictionaries that map code answers to string answers

#prequiz solutions
pre_quiz_correct_answers = ['a','c']

#postquiz solutions
post_quiz_correct_answers = ['b','d','b','a','b','a','d','b']

#for questions self_interest,self_boring,self_confusion,self_easy
self_liker_scale = {
'1':'Strongly disagree'
,'2':'Disagree'
,'3':'Somewhat disagree'
,'4':'Neutral'
,'5':'Somewhat agree'
,'6':'Agree'
,'7':'Strongly agree'
}    

#for demographics
demo_age = {
'a':'18-24'
,'b':'25-34'
,'c':'35-44'
,'d':'44-54'
,'e':'55'
}

demo_gender ={
'a':'Male'
,'b':'Female'
,'c':'Other'
,'d':'Prefer not to say'
}

demo_race ={
'a' : 'White or Caucasian'
,'b' : 'Black or African American'
,'c' : 'Asian'
,'d' : 'Native American or Alaska Native'
,'e' : 'Native Hawaiian or other Pacific Islander'
,'f' : 'None of the above'
,'g' : 'Prefer not to say'
}

demo_ethnicity ={
'a' : 'Hispanic or Latino'
,'b' : 'Not Hispanic or Latino'
,'c' : 'Prefer not to say'
}


demo_marital_status ={
'a':'Single(never married)'
,'b':'Married'
,'c':'Separated'
,'d':'Widowed'
,'e':'Divorced'
,'f':'Prefer not to say'
}

demo_education ={
'a':'High school degree or equivalent'
,'b':'Some college but no degree'
,'c':'Associate degree'
,'d':'Bachelor\'s degree (e.g. BA, BS)'
,'e':'Master\'s degree (e.g. MA, MS,MEd)'
,'f':'Doctorate (e.g. PhD, EdD)'
,'g':'Other(please specify)'
}

demo_income ={
'a':'Less than 25,000'
,'b':'25,000 to 50,000'
,'c':'50,000 to 100,000'
,'d':'100,000 to 150,000'
,'e':'150,000 to 200,000'
,'f':'More than 200,000'
,'g':'Prefer not to say'
,'h':'Not in the United States'
}

demo_employment={
'a':'Employed full-time (40+ hours per week)'
,'b':'Employed part-time (less than 40 hours per week)'
,'c':'Unemployed (currently looking for work)'
,'d':'Unemployed (not currently looking for work)'
,'e':'Student'
,'f':'Retired'
,'g':'Self-employed'
,'h':'Unable to work'
}
    
demo_industry={
'a':'Accounting'
,'b':'Advertising'
,'c':'Aerospace / Aviation / Automotive'
,'d':'Agriculture / Forestry / Fishing'
,'e':'Agriculture / Forestry / Fishing'
,'f':'Biotechnology'
,'g':'Business Services'
,'h':'Computers'
,'i':'Construction / Home Improvement'
,'j':'Consulting'
,'k':'Education'
,'l':'Engineering / Architecture'
,'m':'Entertainment / Recreation'
,'n':'Finance / Banking / Insurance'
,'o':'Food Service'
,'p':'Government / Military'
,'q':'Healthcare / Medical'
,'r':'Internet / Web 2.0'
,'s':'Legal'
,'t':'Manufacturing'
,'u':'Marketing'
,'v':'Media / Publishing'
,'w':'Mining'
,'x':'Non-Profit'
,'y':'Research / Science'
,'z':'Real Estate'
,'A':'Retail'
,'B':'Telecommunication'
,'C':'Utilities'
,'D':'Wholesale'
,'E':'Transportation / Distribution'
,'F':'Other'
,'G':'Don\'t work'
}
    
demo_region={
'a':'Midwest -IA, IL, IN, KS, MI, MN, MO, ND, NE, OH, SD, WI'
,'b':'Northeast - CT, DC, DE, MA, MD, ME, NH, NJ, NY, PA, RI, VT'
,'c':'Southeast - AL, AR, FL, GA, KY, LA, MS, NC, SC, TN, VA, WV'
,'d':'Southwest - AZ, NM, OK, TX'
,'e':'West - AK, CA, CO, HI, ID, MT, NV, OR, UT, WA, WY'
,'f':'Not in the United States'    
}

demo_country={
'00' : 'Select a country'
,'--' : 'Not Specified'
,'AF' : 'Afghanistan'
,'AL' : 'Albania'
,'DZ' : 'Algeria'
,'AS' : 'American Samoa'
,'AD' : 'Andorra'
,'AO' : 'Angola'
,'AI' : 'Anguilla'
,'AQ' : 'Antarctica'
,'AG' : 'Antigua and Barbuda'
,'AR' : 'Argentina'
,'AM' : 'Armenia'
,'AW' : 'Aruba'
,'AU' : 'Australia'
,'AT' : 'Austria'
,'AZ' : 'Azerbaijan'
,'BS' : 'Bahamas'
,'BH' : 'Bahrain'
,'BD' : 'Bangladesh'
,'BB' : 'Barbados'
,'BY' : 'Belarus'
,'BE' : 'Belgium'
,'BZ' : 'Belize'
,'BJ' : 'Benin'
,'BM' : 'Bermuda'
,'BT' : 'Bhutan'
,'BO' : 'Bolivia'
,'BA' : 'Bosnia and Herzegowina'
,'BW' : 'Botswana'
,'BV' : 'Bouvet Island'
,'BR' : 'Brazil'
,'IO' : 'British Indian Ocean Territory'
,'BN' : 'Brunei Darussalam'
,'BG' : 'Bulgaria'
,'BF' : 'Burkina Faso'
,'BI' : 'Burundi'
,'KH' : 'Cambodia'
,'CM' : 'Cameroon'
,'CA' : 'Canada'
,'CV' : 'Cape Verde'
,'KY' : 'Cayman Islands'
,'CF' : 'Central African Republic'
,'TD' : 'Chad'
,'CL' : 'Chile'
,'CN' : 'China'
,'CX' : 'Christmas Island'
,'CC' : 'Cocos (Keeling) Islands'
,'CO' : 'Colombia'
,'KM' : 'Comoros'
,'CG' : 'Congo'
,'CD' : 'Congo, the Democratic Republic of the'
,'CK' : 'Cook Islands'
,'CR' : 'Costa Rica'
,'CI' : "Cote d'Ivoire"
,'HR' : 'Croatia (Hrvatska)'
,'CU' : 'Cuba'
,'CY' : 'Cyprus'
,'CZ' : 'Czech Republic'
,'DK' : 'Denmark'
,'DJ' : 'Djibouti'
,'DM' : 'Dominica'
,'DO' : 'Dominican Republic'
,'TP' : 'East Timor'
,'EC' : 'Ecuador'
,'EG' : 'Egypt'
,'SV' : 'El Salvador'
,'GQ' : 'Equatorial Guinea'
,'ER' : 'Eritrea'
,'EE' : 'Estonia'
,'ET' : 'Ethiopia'
,'FK' : 'Falkland Islands (Malvinas)'
,'FO' : 'Faroe Islands'
,'FJ' : 'Fiji'
,'FI' : 'Finland'
,'FR' : 'France'
,'FX' : 'France, Metropolitan'
,'GF' : 'French Guiana'
,'PF' : 'French Polynesia'
,'TF' : 'French Southern Territories'
,'GA' : 'Gabon'
,'GM' : 'Gambia'
,'GE' : 'Georgia'
,'DE' : 'Germany'
,'GH' : 'Ghana'
,'GI' : 'Gibraltar'
,'GR' : 'Greece'
,'GL' : 'Greenland'
,'GD' : 'Grenada'
,'GP' : 'Guadeloupe'
,'GU' : 'Guam'
,'GT' : 'Guatemala'
,'GN' : 'Guinea'
,'GW' : 'Guinea-Bissau'
,'GY' : 'Guyana'
,'HT' : 'Haiti'
,'HM' : 'Heard and Mc Donald Islands'
,'VA' : 'Holy See (Vatican City State)'
,'HN' : 'Honduras'
,'HK' : 'Hong Kong'
,'HU' : 'Hungary'
,'IS' : 'Iceland'
,'IN' : 'India'
,'ID' : 'Indonesia'
,'IR' : 'Iran (Islamic Republic of)'
,'IQ' : 'Iraq'
,'IE' : 'Ireland'
,'IL' : 'Israel'
,'IT' : 'Italy'
,'JM' : 'Jamaica'
,'JP' : 'Japan'
,'JO' : 'Jordan'
,'KZ' : 'Kazakhstan'
,'KE' : 'Kenya'
,'KI' : 'Kiribati'
,'KP' : "Korea, Democratic People's Republic of"
,'KR' : 'Korea, Republic of'
,'KW' : 'Kuwait'
,'KG' : 'Kyrgyzstan'
,'LA' : "Lao People's Democratic Republic"
,'LV' : 'Latvia'
,'LB' : 'Lebanon'
,'LS' : 'Lesotho'
,'LR' : 'Liberia'
,'LY' : 'Libyan Arab Jamahiriya'
,'LI' : 'Liechtenstein'
,'LT' : 'Lithuania'
,'LU' : 'Luxembourg'
,'MO' : 'Macau'
,'MK' : 'Macedonia, The Former Yugoslav Republic of'
,'MG' : 'Madagascar'
,'MW' : 'Malawi'
,'MY' : 'Malaysia'
,'MV' : 'Maldives'
,'ML' : 'Mali'
,'MT' : 'Malta'
,'MH' : 'Marshall Islands'
,'MQ' : 'Martinique'
,'MR' : 'Mauritania'
,'MU' : 'Mauritius'
,'YT' : 'Mayotte'
,'MX' : 'Mexico'
,'FM' : 'Micronesia, Federated States of'
,'MD' : 'Moldova, Republic of'
,'MC' : 'Monaco'
,'MN' : 'Mongolia'
,'MS' : 'Montserrat'
,'MA' : 'Morocco'
,'MZ' : 'Mozambique'
,'MM' : 'Myanmar'
,'NA' : 'Namibia'
,'NR' : 'Nauru'
,'NP' : 'Nepal'
,'NL' : 'Netherlands'
,'AN' : 'Netherlands Antilles'
,'NC' : 'New Caledonia'
,'NZ' : 'New Zealand'
,'NI' : 'Nicaragua'
,'NE' : 'Niger'
,'NG' : 'Nigeria'
,'NU' : 'Niue'
,'NF' : 'Norfolk Island'
,'MP' : 'Northern Mariana Islands'
,'NO' : 'Norway'
,'OM' : 'Oman'
,'PK' : 'Pakistan'
,'PW' : 'Palau'
,'PA' : 'Panama'
,'PG' : 'Papua New Guinea'
,'PY' : 'Paraguay'
,'PE' : 'Peru'
,'PH' : 'Philippines'
,'PN' : 'Pitcairn'
,'PL' : 'Poland'
,'PT' : 'Portugal'
,'PR' : 'Puerto Rico'
,'QA' : 'Qatar'
,'RE' : 'Reunion'
,'RO' : 'Romania'
,'RU' : 'Russian Federation'
,'RW' : 'Rwanda'
,'KN' : 'Saint Kitts and Nevis'
,'LC' : 'Saint LUCIA'
,'VC' : 'Saint Vincent and the Grenadines'
,'WS' : 'Samoa'
,'SM' : 'San Marino'
,'ST' : 'Sao Tome and Principe'
,'SA' : 'Saudi Arabia'
,'SN' : 'Senegal'
,'SC' : 'Seychelles'
,'SL' : 'Sierra Leone'
,'SG' : 'Singapore'
,'SK' : 'Slovakia (Slovak Republic)'
,'SI' : 'Slovenia'
,'SB' : 'Solomon Islands'
,'SO' : 'Somalia'
,'ZA' : 'South Africa'
,'GS' : 'South Georgia and the South Sandwich Islands'
,'ES' : 'Spain'
,'LK' : 'Sri Lanka'
,'SH' : 'St. Helena'
,'PM' : 'St. Pierre and Miquelon'
,'SD' : 'Sudan'
,'SR' : 'Suriname'
,'SJ' : 'Svalbard and Jan Mayen Islands'
,'SZ' : 'Swaziland'
,'SE' : 'Sweden'
,'CH' : 'Switzerland'
,'SY' : 'Syrian Arab Republic'
,'TW' : 'Taiwan'
,'TJ' : 'Tajikistan'
,'TZ' : 'Tanzania, United Republic of'
,'TH' : 'Thailand'
,'TG' : 'Togo'
,'TK' : 'Tokelau'
,'TO' : 'Tonga'
,'TT' : 'Trinidad and Tobago'
,'TN' : 'Tunisia'
,'TR' : 'Turkey'
,'TM' : 'Turkmenistan'
,'TC' : 'Turks and Caicos Islands'
,'TV' : 'Tuvalu'
,'UG' : 'Uganda'
,'UA' : 'Ukraine'
,'AE' : 'United Arab Emirates'
,'GB' : 'United Kingdom'
,'US' : 'United States'
,'UM' : 'United States Minor Outlying Islands'
,'UY' : 'Uruguay'
,'UZ' : 'Uzbekistan'
,'VU' : 'Vanuatu'
,'VE' : 'Venezuela'
,'VN' : 'Viet Nam'
,'VG' : 'Virgin Islands (British)'
,'VI' : 'Virgin Islands (U.S.)'
,'WF' : 'Wallis and Futuna Islands'
,'EH' : 'Western Sahara'
,'YE' : 'Yemen'
,'YU' : 'Yugoslavia'
,'ZM' : 'Zambia'
,'ZW' : 'Zimbabwe'
}

                  
                  